version: '3'
services:

  querydb:
    image: mongo
    container_name: querydb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmindb
      MONGO_INITDB_ROOT_PASSWORD: secretdb
    ports:
      - 27017:27017
  
  commanddb:
    image: postgres
    container_name: commanddb
    restart: always
    environment: 
      POSTGRES_USER: masaustu
      POSTGRES_PASSWORD: pa55w0rd
    ports: 
      - 5432:5432
  
  infodb:
    image: postgres
    container_name: infodb
    restart: always
    environment: 
      POSTGRES_USER: masaustu
      POSTGRES_PASSWORD: pa55w0rd
    ports: 
      - 5433:5432

  myrabbitmq:
    image: rabbitmq:3-management
    container_name: myrabbitmq
    volumes:
      - ./.docker/rabbitmq/etc/:/etc/rabbitmq/
      - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/
      - ./.docker/rabbitmq/logs/:/var/log/rabbitmq/
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest22
    ports: 
      - 5672:5672

  call_guide_command_api:
    container_name: call_guide_command_api
    build: CallGuideCommand/
    ports: 
      - "8010:80"
    environment:
      - ASPNETCORE_URLS=http://+
      - ASPNETCORE_ENVIRONMENT=Development
      - PostgreSqlConnectionString=User ID =masaustu;Password=pa55w0rd;Server=commanddb;Database=CallGuideCommand;Integrated Security=true;Pooling=true;
      - RabbitMQConf:Uri=rabbitmq://guest:guest22@myrabbitmq/
    volumes:
      - ${APPDATA}\microsoft\UserSecrets\:/root/.microsoft/usersecrets
    depends_on: 
      - commanddb
      - myrabbitmq

  call_guide_query_api:
    container_name: call_guide_query_api
    build: CallGuideQuery/
    ports: 
      - "8020:80"
    environment:
      - ASPNETCORE_URLS=http://+
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoSettings:ConnectionString=mongodb://mongoadmindb:secretdb@querydb:27017/?authSource=admin
      - RabbitMQConf:Uri=rabbitmq://guest:guest22@myrabbitmq/
    volumes:
      - ${APPDATA}\microsoft\UserSecrets\:/root/.microsoft/usersecrets
    depends_on: 
      - querydb
      - myrabbitmq

  info_api:
    container_name: info_api
    build: CommunicationInformation/
    ports: 
      - "8030:80"
    environment:
      - ASPNETCORE_URLS=http://+
      - ASPNETCORE_ENVIRONMENT=Development
      - PostgreSqlConnectionString=User ID =masaustu;Password=pa55w0rd;Server=infodb;Database=cominfo;Integrated Security=true;Pooling=true;
      - RabbitMQConf:Uri=rabbitmq://guest:guest22@myrabbitmq/
    volumes:
      - ${APPDATA}\microsoft\UserSecrets\:/root/.microsoft/usersecrets
    depends_on: 
      - infodb
      - myrabbitmq